version: 2
jobs:
  build:
    working_directory: ~/GettingStartedWithKotlin
    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:
      - checkout
      - run: ./gradlew test
      - store_test_results:
          path: build/test-results
